export enum MatriculaSituacao {
    ATIVO = 'ATIVO',
    TRANCADO = 'TRANCADO',
    CANCELADO = 'CANCELADO',
    AGUARDANDO_CONFIRMACAO = 'AGUARDANDO_CONFIRMACAO',
    TRANSFERIDO = 'TRANSFERIDO',
    SUSPENSO = 'SUSPENSO',
    DESISTENCIA = 'DESISTENCIA'
}
